import { ApiError } from "../types";
import { Language, MessageCode } from "../types/message";

export const MESSAGE_MAPPINGS = {
  "en": {
    "FOOD_NAME_REQUIRED": "Food name is required and cannot be empty",
    "FOOD_NAME_TOO_LONG": "Food name cannot exceed 100 characters",
    "CALORIES_MUST_BE_NUMBER": "Calories must be a valid number",
    "CALORIES_TOO_LOW": "Calories cannot be negative",
    "CALORIES_REQUIRED": "Calories field is required",
    "PROTEIN_MUST_BE_NUMBER": "Protein must be a valid number",
    "PROTEIN_TOO_LOW": "Protein cannot be negative",
    "PROTEIN_REQUIRED": "Protein field is required",
    "CARBS_MUST_BE_NUMBER": "Carbohydrates must be a valid number",
    "CARBS_TOO_LOW": "Carbohydrates cannot be negative",
    "CARBS_REQUIRED": "Carbohydrates field is required",
    "FAT_MUST_BE_NUMBER": "Fat must be a valid number",
    "FAT_TOO_LOW": "Fat cannot be negative",
    "FAT_REQUIRED": "Fat field is required",
    "FIBER_MUST_BE_NUMBER": "Fiber must be a valid number",
    "FIBER_TOO_LOW": "Fiber cannot be negative",
    "SUGAR_MUST_BE_NUMBER": "Sugar must be a valid number",
    "SUGAR_TOO_LOW": "Sugar cannot be negative",
    "SODIUM_MUST_BE_NUMBER": "Sodium must be a valid number",
    "SODIUM_TOO_LOW": "Sodium cannot be negative",
    "CATEGORY_MUST_BE_STRING": "Category must be a text value",
    "INVALID_CATEGORY": "Invalid food category selected",
    "BRAND_MUST_BE_STRING": "Brand must be a text value",
    "BARCODE_MUST_BE_STRING": "Barcode must be a text value",
    "SERVING_AMOUNT_MUST_BE_NUMBER": "Serving amount must be a valid number",
    "SERVING_AMOUNT_MUST_BE_POSITIVE": "Serving amount must be positive",
    "SERVING_UNIT_MUST_BE_STRING": "Serving unit must be a text value",
    "SERVING_SIZE_MUST_BE_OBJECT": "Serving size must be an object",
    "IS_PUBLIC_MUST_BE_BOOLEAN": "Public status must be true or false",
    "FOOD_ITEM_ID_REQUIRED": "Food item ID is required",
    "QUANTITY_MUST_BE_NUMBER": "Quantity must be a valid number",
    "QUANTITY_MUST_BE_POSITIVE": "Quantity must be positive",
    "QUANTITY_REQUIRED": "Quantity field is required",
    "UNIT_REQUIRED": "Unit field is required",
    "INVALID_UNIT": "Invalid unit selected",
    "MEAL_TYPE_REQUIRED": "Meal type field is required",
    "INVALID_MEAL_TYPE": "Invalid meal type selected",
    "INVALID_TIMESTAMP_FORMAT": "Invalid timestamp format",
    "TIMESTAMP_MUST_BE_ISO_FORMAT": "Timestamp must be in ISO format",
    "CALORIES_TOO_HIGH": "Daily calories cannot exceed 5000",
    "PROTEIN_TOO_HIGH": "Daily protein cannot exceed 300g",
    "CARBS_TOO_HIGH": "Daily carbohydrates cannot exceed 500g",
    "FAT_TOO_HIGH": "Daily fat cannot exceed 200g",
    "WATER_MUST_BE_NUMBER": "Water intake must be a valid number",
    "WATER_TOO_LOW": "Water intake cannot be less than 1000ml",
    "WATER_TOO_HIGH": "Water intake cannot exceed 5000ml",
    "WATER_REQUIRED": "Water intake field is required",
    "ACTIVITY_LEVEL_MUST_BE_STRING": "Activity level must be a text value",
    "INVALID_ACTIVITY_LEVEL": "Invalid activity level selected",
    "GOAL_MUST_BE_STRING": "Goal must be a text value",
    "INVALID_GOAL": "Invalid goal selected",
    "RECORD_CREATED": "Personal record added successfully",
    "RECORD_DELETED": "Personal record deleted successfully",
    "RECORD_UPDATED": "Personal record updated successfully",
    "SEARCH_QUERY_TOO_SHORT": "Search query must be at least 2 characters long",
    "GOALS_CREATED": "Nutrition goals created successfully",
    "GOALS_UPDATED": "Nutrition goals updated successfully",
    "MEAL_ADDED": "Meal added successfully",
    "PROFILE_NOT_FOUND": "Profile not found",
    "FOOD_NAME_AND_CALORIES_REQUIRED": "Food name and calories are required",
    "DATE_CANNOT_BE_PAST": "Date cannot be in the past",
    "USER_UPDATED": "User updated successfully",
    "PASSWORD_CHANGED": "Password changed successfully",
    "EMAIL_VERIFICATION_FAILED": "Email verification failed",
    "EMAIL_VERIFICATION_SUCCESS": "Email verification successful",
    "CANNOT_ADD_SELF": "Cannot add yourself to your friends list",
    "FRIENDSHIP_NOT_ALLOWED": "The recipient has not allowed this friend request.",
    "FRIEND_REQUEST_SENT": "Friend request sent successfully.",
    "ALREADY_FRIENDS": "You are already friends",
    "GOALS_NOT_FOUND": "Aucun objectif trouvé",
    "GOAL_DELETED": "Goal deleted successfully",
    "TITLE_REQUIRED": "Title is required",
    "TITLE_TOO_LONG": "Title must not exceed 100 characters",
    "DESCRIPTION_TOO_LONG": "Description must not exceed 500 characters",
    "CATEGORY_REQUIRED": "Category is required",
    "TARGET_MUST_BE_NUMBER": "Target must be a number",
    "TARGET_MUST_BE_POSITIVE": "Target must be a positive number",
    "TARGET_REQUIRED": "Target is required",
    "INVALID_DEADLINE_FORMAT": "Invalid deadline format",
    "DEADLINE_MUST_BE_ISO": "Deadline must be in ISO format",
    "DEADLINE_MUST_BE_FUTURE": "Deadline must be a future date",
    "DEADLINE_REQUIRED": "Deadline is required",
    "INVALID_PRIORITY": "Invalid priority level",
    "CURRENT_MUST_BE_NUMBER": "Current value must be a number",
    "CURRENT_TOO_LOW": "Current value cannot be negative",
    "COMPLETED_MUST_BE_BOOLEAN": "Completed status must be true or false",
    "VALUE_MUST_BE_NUMBER": "Progress value must be a number",
    "VALUE_TOO_LOW": "Progress value cannot be negative",
    "VALUE_REQUIRED": "Progress value is required",
    "NOTES_TOO_LONG": "Notes must not exceed 200 characters",
    "EVENTS_RETRIEVED": "Events retrieved successfully",
    "EVENT_RETRIEVED": "Event retrieved successfully",
    "EVENT_CREATED": "Event created successfully",
    "EVENT_UPDATED": "Event updated successfully",
    "EVENT_DELETED": "Event deleted successfully",
    "EVENT_COMPLETED": "Event marked as completed",
    "UPCOMING_EVENTS_RETRIEVED": "Upcoming events retrieved successfully",
    "EVENT_NOT_FOUND": "Event not found",
    "EVENT_ALREADY_COMPLETED": "Event is already completed",
    "DATE_REQUIRED": "Date is required",
    "INVALID_DATE_FORMAT": "Invalid date format",
    "DATE_MUST_BE_ISO_FORMAT": "Date must be in ISO format (YYYY-MM-DD)",
    "INVALID_TIME_FORMAT": "Invalid time format. Use HH:MM format",
    "ACTIVITY_TYPE_REQUIRED": "Activity type is required",
    "INVALID_ACTIVITY_TYPE": "Invalid activity type",
    "DISTANCE_TOO_LOW": "Distance cannot be negative",
    "DISTANCE_TOO_HIGH": "Distance cannot exceed 1000 km",
    "INVALID_DURATION_FORMAT": "Invalid duration format. Use HH:MM:SS or MM:SS format",
    "LOCATION_TOO_LONG": "Location cannot exceed 200 characters",
    "EVENT_NOTES_TOO_LONG": "Notes cannot exceed 500 characters",
    "ACCOUNT_UNVERIFIED": "Your account is not verified",
    "FIRST_RUN_TITLE": "First Steps",
    "FIRST_RUN_DESC": "Completed your first run",
    "DISTANCE_5K_TITLE": "5K Club",
    "DISTANCE_5K_DESC": "Completed a 5 kilometer run",
    "DISTANCE_10K_TITLE": "10K Club",
    "DISTANCE_10K_DESC": "Completed a 10 kilometer run",
    "HALF_MARATHON_TITLE": "Half Marathoner",
    "HALF_MARATHON_DESC": "Completed a half marathon (21.1 km)",
    "MARATHON_TITLE": "Marathoner",
    "MARATHON_DESC": "Completed a full marathon (42.2 km)",
    "ULTRA_MARATHON_TITLE": "Ultra Marathoner",
    "ULTRA_MARATHON_DESC": "Completed an ultra marathon (50 km)",
    "EARLY_BIRD_TITLE": "Early Bird",
    "EARLY_BIRD_DESC": "Completed 5 runs before 7 AM",
    "WEEK_STREAK_TITLE": "Weekly Streak",
    "WEEK_STREAK_DESC": "Ran for 7 consecutive days",
    "MONTH_STREAK_TITLE": "Monthly Streak",
    "MONTH_STREAK_DESC": "Ran for 30 consecutive days",
    "SPEED_DEMON_TITLE": "Speed Demon",
    "SPEED_DEMON_DESC": "Ran 1 km in under 4 minutes",
    "SPEED_KING_TITLE": "Speed King",
    "SPEED_KING_DESC": "Ran 1 km in under 3 minutes 30 seconds",
    "ELEVATION_MASTER_TITLE": "Elevation Master",
    "ELEVATION_MASTER_DESC": "Accumulated 1000m of elevation gain",
    "MOUNTAIN_GOAT_TITLE": "Mountain Goat",
    "MOUNTAIN_GOAT_DESC": "Accumulated 5000m of elevation gain",
    "TOTAL_100K_TITLE": "100K Club",
    "TOTAL_100K_DESC": "Ran a total of 100 kilometers",
    "TOTAL_500K_TITLE": "500K Club",
    "TOTAL_500K_DESC": "Ran a total of 500 kilometers",
    "TOTAL_1000K_TITLE": "1000K Club",
    "TOTAL_1000K_DESC": "Ran a total of 1000 kilometers",
    "NIGHT_RUNNER_TITLE": "Night Runner",
    "NIGHT_RUNNER_DESC": "Completed 5 runs after 8 PM",
    "WEEKEND_WARRIOR_TITLE": "Weekend Warrior",
    "WEEKEND_WARRIOR_DESC": "Completed 10 runs on weekends",
    "FIRST_10_RUNS_TITLE": "First 10 Runs",
    "FIRST_10_RUNS_DESC": "Completed your first 10 runs",
    "FIRST_50_RUNS_TITLE": "First 50 Runs",
    "FIRST_50_RUNS_DESC": "Completed your first 50 runs",
    "FIRST_100_RUNS_TITLE": "First 100 Runs",
    "FIRST_100_RUNS_DESC": "Completed your first 100 runs",
    "RAIN_RUNNER_TITLE": "Rain Runner",
    "RAIN_RUNNER_DESC": "Completed 5 runs in the rain",
    "FOUR_SEASONS_TITLE": "Four Seasons Runner",
    "FOUR_SEASONS_DESC": "Ran in all four seasons",
    "SOCIAL_BUTTERFLY_TITLE": "Social Butterfly",
    "SOCIAL_BUTTERFLY_DESC": "Completed 5 group runs",
    "EXPLORER_TITLE": "Explorer",
    "EXPLORER_DESC": "Ran on 10 different routes",
    "TRAIL_BLAZER_TITLE": "Trail Blazer",
    "TRAIL_BLAZER_DESC": "Completed 20 trail runs",
    "CITY_RUNNER_TITLE": "City Runner",
    "CITY_RUNNER_DESC": "Completed 15 urban runs",
    "HEART_RATE_ACHIEVER_TITLE": "Heart Rate Achiever",
    "HEART_RATE_ACHIEVER_DESC": "Completed 10 runs in target heart rate zone",
    "CONSISTENT_PACER_TITLE": "Consistent Pacer",
    "CONSISTENT_PACER_DESC": "Maintained consistent pace in 10 runs",
    "NEGATIVE_SPLIT_TITLE": "Negative Split Master",
    "NEGATIVE_SPLIT_DESC": "Completed 5 runs with negative splits",
    "FIRST_YEAR_TITLE": "First Year Runner",
    "FIRST_YEAR_DESC": "Ran for 365 days",
    "ACHIEVEMENTS_RETRIEVED": "Achievements retrieved successfully",
    "ACHIEVEMENTS_RETRIEVE_FAILED": "Failed to retrieve achievements",
    "ACHIEVEMENT_NOT_FOUND": "Achievement not found",
    "INVALID_DATA": "Invalid data provided",
    "ACHIEVEMENT_ALREADY_UNLOCKED": "Achievement already unlocked",
    "ACHIEVEMENT_UNLOCKED": "Achievement unlocked successfully",
    "ACHIEVEMENT_UNLOCK_FAILED": "Failed to unlock achievement",
    "ACHIEVEMENTS_CHECKED": "Achievements checked successfully",
    "ACHIEVEMENTS_CHECK_FAILED": "Failed to check achievements",
    "ACHIEVEMENT_STATS_RETRIEVED": "Achievement statistics retrieved successfully",
    "ACHIEVEMENT_STATS_RETRIEVE_FAILED": "Failed to retrieve achievement statistics",
    "AVAILABLE_ACHIEVEMENTS_RETRIEVED": "Available achievements retrieved successfully",
    "AVAILABLE_ACHIEVEMENTS_RETRIEVE_FAILED": "Failed to retrieve available achievements",
    "TOKEN_EXPIRED": "Your session token has expired",
    "GETTTING_ALL_SUGGESTION_FAILED": "Failed to get all suggestions",
    "GETTING_NUTRITION_FAILED": "Failed to get nutrition tips",
    "ERROR_GETTING_TRAINING_PLANT": "Error getting training plan",
    "ERROR_GETTING_WORKOUT": "Error getting workout suggestions",
    "ERROR_GETTING_MOTIVATION": "Error getting motivation message",
    "NO_SUGGESTIONS_FOUND": "No suggestions found",
    "NO_PLANTS_FOUND": "No training plans found",
    "NO_WORKOUTS_FOUND": "No workouts found",
    "NO_MOTIVATION_FOUND": "No motivation message found",
    "ERROR_SENDING_MESSAGE": "Error sending message",
    "MESSAGE_SEND_SUCCESS": "Message sent successfully",
    "MESSAGE_TEXT_REQUIRED": "Message text is required",
    "MESSAGES_RETRIEVED": "Messages retrieved successfully",
    "ERROR_RETRIEVING_MESSAGES": "Error retrieving messages",
    "ERROR_GETTING_SLEEP_DATA": "Error getting sleep data",
    "SLEEP_DATA_RETRIEVED": "Sleep data retrieved successfully",
    "ERROR_GETTING_PERSONAL_RECORDS": "Error getting personal records",
    "PERSONAL_RECORDS_RETRIEVED": "Personal records retrieved successfully",
    "ERROR_GETTING_ACTIVITY_TYPE_DATA": "Error getting activity type data",
    "ACTIVITY_TYPE_DATA_RETRIEVED": "Activity type data retrieved successfully",
    "ERROR_GETTING_PACE_DATA": "Error getting pace data",
    "PACE_DATA_RETRIEVED": "Pace data retrieved successfully",
    "ERROR_GETTING_MONTHLY_DATA": "Error getting monthly data",
    "MONTHLY_DATA_RETRIEVED": "Monthly data retrieved successfully",
    "ERROR_GETTING_WEEKLY_DATA": "Error getting weekly data",
    "WEEKLY_DATA_RETRIEVED": "Weekly data retrieved successfully",
    "ERROR_GETTING_STATISTICS": "Error getting statistics",
    "STATISTICS_RETRIEVED": "Statistics retrieved successfully",
    "DATA_SHARING_PREFERENCES_UPDATED": "Data sharing preferences updated successfully",
    "DATA_SHARING_PREFERENCES_UPDATE_FAILED": "Failed to update data sharing preferences"
  },
  "fr": {
    "FOOD_NAME_REQUIRED": "Le nom de l'aliment est requis et ne peut pas être vide",
    "FOOD_NAME_TOO_LONG": "Le nom de l'aliment ne peut pas dépasser 100 caractères",
    "CALORIES_MUST_BE_NUMBER": "Les calories doivent être un nombre valide",
    "CALORIES_TOO_LOW": "Les calories ne peuvent pas être négatives",
    "CALORIES_REQUIRED": "Le champ calories est obligatoire",
    "PROTEIN_MUST_BE_NUMBER": "Les protéines doivent être un nombre valide",
    "PROTEIN_TOO_LOW": "Les protéines ne peuvent pas être négatives",
    "PROTEIN_REQUIRED": "Le champ protéines est obligatoire",
    "CARBS_MUST_BE_NUMBER": "Les glucides doivent être un nombre valide",
    "CARBS_TOO_LOW": "Les glucides ne peuvent pas être négatives",
    "CARBS_REQUIRED": "Le champ glucides est obligatoire",
    "FAT_MUST_BE_NUMBER": "Les lipides doivent être un nombre valide",
    "FAT_TOO_LOW": "Les lipides ne peuvent pas être négatives",
    "FAT_REQUIRED": "Le champ lipides est obligatoire",
    "FIBER_MUST_BE_NUMBER": "Les fibres doivent être un nombre valide",
    "FIBER_TOO_LOW": "Les fibres ne peuvent pas être négatives",
    "SUGAR_MUST_BE_NUMBER": "Le sucre doit être un nombre valide",
    "SUGAR_TOO_LOW": "Le sucre ne peut pas être négatif",
    "SODIUM_MUST_BE_NUMBER": "Le sodium doit être un nombre valide",
    "SODIUM_TOO_LOW": "Le sodium ne peut pas être négatif",
    "CATEGORY_MUST_BE_STRING": "La catégorie doit être une valeur textuelle",
    "INVALID_CATEGORY": "Catégorie d'aliment invalide sélectionnée",
    "BRAND_MUST_BE_STRING": "La marque doit être une valeur textuelle",
    "BARCODE_MUST_BE_STRING": "Le code-barres doit être une valeur textuelle",
    "SERVING_AMOUNT_MUST_BE_NUMBER": "La quantité de portion doit être un nombre valide",
    "SERVING_AMOUNT_MUST_BE_POSITIVE": "La quantité de portion doit être positive",
    "SERVING_UNIT_MUST_BE_STRING": "L'unité de portion doit être une valeur textuelle",
    "SERVING_SIZE_MUST_BE_OBJECT": "La taille de portion doit être un objet",
    "IS_PUBLIC_MUST_BE_BOOLEAN": "Le statut public doit être vrai ou faux",
    "FOOD_ITEM_ID_REQUIRED": "L'ID de l'aliment est requis",
    "QUANTITY_MUST_BE_NUMBER": "La quantité doit être un nombre valide",
    "QUANTITY_MUST_BE_POSITIVE": "La quantité doit être positive",
    "QUANTITY_REQUIRED": "Le champ quantité est obligatoire",
    "UNIT_REQUIRED": "Le champ unité est obligatoire",
    "INVALID_UNIT": "Unité invalide sélectionnée",
    "MEAL_TYPE_REQUIRED": "Le champ type de repas est obligatoire",
    "INVALID_MEAL_TYPE": "Type de repas invalide sélectionné",
    "INVALID_TIMESTAMP_FORMAT": "Format d'horodatage invalide",
    "TIMESTAMP_MUST_BE_ISO_FORMAT": "L'horodatage doit être au format ISO",
    "CALORIES_TOO_HIGH": "Les calories quotidiennes ne peuvent pas dépasser 5000",
    "PROTEIN_TOO_HIGH": "Les protéines quotidiennes ne peuvent pas dépasser 300g",
    "CARBS_TOO_HIGH": "Les glucides quotidiens ne peuvent pas dépasser 500g",
    "FAT_TOO_HIGH": "Les lipides quotidiens ne peuvent pas dépasser 200g",
    "WATER_MUST_BE_NUMBER": "La consommation d'eau doit être un nombre valide",
    "WATER_TOO_LOW": "La consommation d'eau ne peut pas être inférieure à 1000ml",
    "WATER_TOO_HIGH": "La consommation d'eau ne peut pas dépasser 5000ml",
    "WATER_REQUIRED": "Le champ consommation d'eau est obligatoire",
    "ACTIVITY_LEVEL_MUST_BE_STRING": "Le niveau d'activité doit être une valeur textuelle",
    "INVALID_ACTIVITY_LEVEL": "Niveau d'activité invalide sélectionné",
    "GOAL_MUST_BE_STRING": "L'objectif doit être une valeur textuelle",
    "INVALID_GOAL": "Objectif invalide sélectionné",
    "RECORD_CREATED": "Record personnel ajouté avec succès",
    "RECORD_DELETED": "Record personnel supprimé avec succès",
    "RECORD_UPDATED": "Record personnel mis à jour avec succès",
    "SEARCH_QUERY_TOO_SHORT": "La requête de recherche doit contenir au moins 2 caractères",
    "GOALS_CREATED": "Objectifs nutritionnels créés avec succès",
    "GOALS_UPDATED": "Objectifs nutritionnels mis à jour avec succès",
    "MEAL_ADDED": "Repas ajouté avec succès",
    "PROFILE_NOT_FOUND": "Profil non trouvé",
    "FOOD_NAME_AND_CALORIES_REQUIRED": "Le nom de l'aliment et les calories sont requis",
    "DATE_CANNOT_BE_PAST": "La date du ne peut être une date passée",
    "USER_UPDATED": "Profil mis à jour avec succès",
    "PASSWORD_CHANGED": "Mot de passe modifié avec succès",
    "EMAIL_VERIFICATION_FAILED": "Email verification failed",
    "EMAIL_VERIFICATION_SUCCESS": "Email verification successful",
    "CANNOT_ADD_SELF": "Vous ne pouvez vous ajouter vous-mêmes à votre liste d'ami.e.s",
    "FRIENDSHIP_NOT_ALLOWED": "Le destinataire n'a pas autorisé cette demande d'ami.",
    "FRIEND_REQUEST_SENT": "Demande d'ami envoyée avec succès.",
    "ALREADY_FRIENDS": "Vous êtes déjà amis avec cet utilisateur",
    "GOALS_NOT_FOUND": "Aucun objectif trouvé",
    "GOAL_DELETED": "Objectif supprimé avec succès",
    "TITLE_REQUIRED": "Le titre est requis",
    "TITLE_TOO_LONG": "Le titre ne doit pas dépasser 100 caractères",
    "DESCRIPTION_TOO_LONG": "La description ne doit pas dépasser 500 caractères",
    "CATEGORY_REQUIRED": "La catégorie est requise",
    "TARGET_MUST_BE_NUMBER": "La cible doit être un nombre",
    "TARGET_MUST_BE_POSITIVE": "La cible doit être un nombre positif",
    "TARGET_REQUIRED": "La cible est requise",
    "INVALID_DEADLINE_FORMAT": "Format de date limite invalide",
    "DEADLINE_MUST_BE_ISO": "La date limite doit être au format ISO",
    "DEADLINE_MUST_BE_FUTURE": "La date limite doit être une date future",
    "DEADLINE_REQUIRED": "La date limite est requise",
    "INVALID_PRIORITY": "Niveau de priorité invalide",
    "CURRENT_MUST_BE_NUMBER": "La valeur actuelle doit être un nombre",
    "CURRENT_TOO_LOW": "La valeur actuelle ne peut pas être négative",
    "COMPLETED_MUST_BE_BOOLEAN": "Le statut complété doit être vrai ou faux",
    "VALUE_MUST_BE_NUMBER": "La valeur de progression doit être un nombre",
    "VALUE_TOO_LOW": "La valeur de progression ne peut pas être négative",
    "VALUE_REQUIRED": "La valeur de progression est requise",
    "NOTES_TOO_LONG": "Les notes ne doivent pas dépasser 200 caractères",
    "EVENTS_RETRIEVED": "Événements récupérés avec succès",
    "EVENT_RETRIEVED": "Événement récupéré avec succès",
    "EVENT_CREATED": "Événement créé avec succès",
    "EVENT_UPDATED": "Événement mis à jour avec succès",
    "EVENT_DELETED": "Événement supprimé avec succès",
    "EVENT_COMPLETED": "Événement marqué comme terminé",
    "UPCOMING_EVENTS_RETRIEVED": "Événements à venir récupérés avec succès",
    "EVENT_NOT_FOUND": "Événement non trouvé",
    "EVENT_ALREADY_COMPLETED": "L'événement est déjà terminé",
    "DATE_REQUIRED": "La date est requise",
    "INVALID_DATE_FORMAT": "Format de date invalide",
    "DATE_MUST_BE_ISO_FORMAT": "La date doit être au format ISO (AAAA-MM-JJ)",
    "INVALID_TIME_FORMAT": "Format d'heure invalide. Utilisez le format HH:MM",
    "ACTIVITY_TYPE_REQUIRED": "Le type d'activité est requis",
    "INVALID_ACTIVITY_TYPE": "Type d'activité invalide",
    "DISTANCE_TOO_LOW": "La distance ne peut pas être négative",
    "DISTANCE_TOO_HIGH": "La distance ne peut pas dépasser 1000 km",
    "INVALID_DURATION_FORMAT": "Format de durée invalide. Utilisez le format HH:MM:SS ou MM:SS",
    "LOCATION_TOO_LONG": "L'emplacement ne peut pas dépasser 200 caractères",
    "EVENT_NOTES_TOO_LONG": "Les notes ne peuvent pas dépasser 500 caractères",
    "ACCOUNT_UNVERIFIED": "Votre compte n'est pas vérifié",
    "FIRST_RUN_TITLE": "Premier Pas",
    "FIRST_RUN_DESC": "Complété votre première course",
    "DISTANCE_5K_TITLE": "Club 5K",
    "DISTANCE_5K_DESC": "Complété une course de 5 kilomètres",
    "DISTANCE_10K_TITLE": "Club 10K",
    "DISTANCE_10K_DESC": "Complété une course de 10 kilomètres",
    "HALF_MARATHON_TITLE": "Semi-Marathonien",
    "HALF_MARATHON_DESC": "Complété un semi-marathon (21.1 km)",
    "MARATHON_TITLE": "Marathonien",
    "MARATHON_DESC": "Complété un marathon complet (42.2 km)",
    "ULTRA_MARATHON_TITLE": "Ultra-Marathonien",
    "ULTRA_MARATHON_DESC": "Complété un ultra-marathon (50 km)",
    "EARLY_BIRD_TITLE": "Lève-tôt",
    "EARLY_BIRD_DESC": "Complété 5 courses avant 7h du matin",
    "WEEK_STREAK_TITLE": "Série Hebdomadaire",
    "WEEK_STREAK_DESC": "Couru 7 jours consécutifs",
    "MONTH_STREAK_TITLE": "Série Mensuelle",
    "MONTH_STREAK_DESC": "Couru 30 jours consécutifs",
    "SPEED_DEMON_TITLE": "Démon de Vitesse",
    "SPEED_DEMON_DESC": "Couru 1 km en moins de 4 minutes",
    "SPEED_KING_TITLE": "Roi de la Vitesse",
    "SPEED_KING_DESC": "Couru 1 km en moins de 3 minutes 30 secondes",
    "ELEVATION_MASTER_TITLE": "Maître de l'Élévation",
    "ELEVATION_MASTER_DESC": "Accumulé 1000m de dénivelé positif",
    "MOUNTAIN_GOAT_TITLE": "Chèvre de Montagne",
    "MOUNTAIN_GOAT_DESC": "Accumulé 5000m de dénivelé positif",
    "TOTAL_100K_TITLE": "Club 100K",
    "TOTAL_100K_DESC": "Couru un total de 100 kilomètres",
    "TOTAL_500K_TITLE": "Club 500K",
    "TOTAL_500K_DESC": "Couru un total de 500 kilomètres",
    "TOTAL_1000K_TITLE": "Club 1000K",
    "TOTAL_1000K_DESC": "Couru un total de 1000 kilomètres",
    "NIGHT_RUNNER_TITLE": "Coureur Nocturne",
    "NIGHT_RUNNER_DESC": "Complété 5 courses après 20h",
    "WEEKEND_WARRIOR_TITLE": "Guerrier du Weekend",
    "WEEKEND_WARRIOR_DESC": "Complété 10 courses le weekend",
    "FIRST_10_RUNS_TITLE": "Premières 10 Courses",
    "FIRST_10_RUNS_DESC": "Complété vos 10 premières courses",
    "FIRST_50_RUNS_TITLE": "Premières 50 Courses",
    "FIRST_50_RUNS_DESC": "Complété vos 50 premières courses",
    "FIRST_100_RUNS_TITLE": "Premières 100 Courses",
    "FIRST_100_RUNS_DESC": "Complété vos 100 premières courses",
    "RAIN_RUNNER_TITLE": "Coureur sous la Pluie",
    "RAIN_RUNNER_DESC": "Complété 5 courses sous la pluie",
    "FOUR_SEASONS_TITLE": "Coureur des Quatre Saisons",
    "FOUR_SEASONS_DESC": "Couru dans les quatre saisons",
    "SOCIAL_BUTTERFLY_TITLE": "Papillon Social",
    "SOCIAL_BUTTERFLY_DESC": "Complété 5 courses en groupe",
    "EXPLORER_TITLE": "Explorateur",
    "EXPLORER_DESC": "Couru sur 10 parcours différents",
    "TRAIL_BLAZER_TITLE": "Pionnier des Sentiers",
    "TRAIL_BLAZER_DESC": "Complété 20 courses en sentier",
    "CITY_RUNNER_TITLE": "Coureur Urbain",
    "CITY_RUNNER_DESC": "Complété 15 courses en ville",
    "HEART_RATE_ACHIEVER_TITLE": "Maître du Rythme Cardiaque",
    "HEART_RATE_ACHIEVER_DESC": "Complété 10 courses en zone cardiaque cible",
    "CONSISTENT_PACER_TITLE": "Rythme Régulier",
    "CONSISTENT_PACER_DESC": "Maintenu un rythme constant sur 10 courses",
    "NEGATIVE_SPLIT_TITLE": "Maître du Split Négatif",
    "NEGATIVE_SPLIT_DESC": "Complété 5 courses avec splits négatifs",
    "FIRST_YEAR_TITLE": "Première Année de Course",
    "FIRST_YEAR_DESC": "Couru pendant 365 jours",
    "ACHIEVEMENTS_RETRIEVED": "Achievements récupérés avec succès",
    "ACHIEVEMENTS_RETRIEVE_FAILED": "Échec de la récupération des achievements",
    "ACHIEVEMENT_NOT_FOUND": "Achievement non trouvé",
    "INVALID_DATA": "Données invalides",
    "ACHIEVEMENT_ALREADY_UNLOCKED": "Achievement déjà débloqué",
    "ACHIEVEMENT_UNLOCKED": "Achievement débloqué avec succès",
    "ACHIEVEMENT_UNLOCK_FAILED": "Échec du déblocage de l'achievement",
    "ACHIEVEMENTS_CHECKED": "Achievements vérifiés avec succès",
    "ACHIEVEMENTS_CHECK_FAILED": "Échec de la vérification des achievements",
    "ACHIEVEMENT_STATS_RETRIEVED": "Statistiques des achievements récupérées avec succès",
    "ACHIEVEMENT_STATS_RETRIEVE_FAILED": "Échec de la récupération des statistiques des achievements",
    "AVAILABLE_ACHIEVEMENTS_RETRIEVED": "Achievements disponibles récupérés avec succès",
    "AVAILABLE_ACHIEVEMENTS_RETRIEVE_FAILED": "Échec de la récupération des achievements disponibles",
    "TOKEN_EXPIRED": "Le token de votre session a expiré",
    "GETTTING_ALL_SUGGESTION_FAILED": "Échec de la récupération des suggestions",
    "GETTING_NUTRITION_FAILED": "Échec de la récupération des conseils nutritionnels",
    "ERROR_GETTING_TRAINING_PLANT": "Erreur lors de la récupération du plan d'entraînement",
    "ERROR_GETTING_WORKOUT": "Erreur lors de la récupération des suggestions d'entraînement",
    "ERROR_GETTING_MOTIVATION": "Erreur lors de la récupération du message de motivation",
    "NO_SUGGESTIONS_FOUND": "Aucune suggestion trouvée",
    "NO_PLANTS_FOUND": "Aucun plan d'entraînement trouvé",
    "NO_WORKOUTS_FOUND": "Aucun entraînement trouvé",
    "NO_MOTIVATION_FOUND": "Aucun message de motivation trouvé",
    "ERROR_SENDING_MESSAGE": "Erreur lors de l'envoi du message",
    "MESSAGE_SEND_SUCCESS": "Message envoyé avec succès",
    "MESSAGE_TEXT_REQUIRED": "Le texte du message est requis",
    "MESSAGES_RETRIEVED": "Messages récupérés avec succès",
    "ERROR_RETRIEVING_MESSAGES": "Erreur lors de la récupération des messages",
    "ERROR_GETTING_SLEEP_DATA": "Erreur lors de la récupération des données de sommeil",
    "SLEEP_DATA_RETRIEVED": "Données de sommeil récupérées avec succès",
    "ERROR_GETTING_PERSONAL_RECORDS": "Erreur lors de la récupération des records personnels",
    "PERSONAL_RECORDS_RETRIEVED": "Records personnels récupérés avec succès",
    "ERROR_GETTING_ACTIVITY_TYPE_DATA": "Erreur lors de la récupération des données de type d'activité",
    "ACTIVITY_TYPE_DATA_RETRIEVED": "Données de type d'activité récupérées avec succès",
    "ERROR_GETTING_PACE_DATA": "Erreur lors de la récupération des données d'allure",
    "PACE_DATA_RETRIEVED": "Données d'allure récupérées avec succès",
    "ERROR_GETTING_MONTHLY_DATA": "Erreur lors de la récupération des données mensuelles",
    "MONTHLY_DATA_RETRIEVED": "Données mensuelles récupérées avec succès",
    "ERROR_GETTING_WEEKLY_DATA": "Erreur lors de la récupération des données hebdomadaires",
    "WEEKLY_DATA_RETRIEVED": "Données hebdomadaires récupérées avec succès",
    "ERROR_GETTING_STATISTICS": "Erreur lors de la récupération des statistiques",
    "STATISTICS_RETRIEVED": "Statistiques récupérées avec succès",
    "DATA_SHARING_PREFERENCES_UPDATED": "Préférences de partage de données mises à jour avec succès",
    "DATA_SHARING_PREFERENCES_UPDATE_FAILED": "Échec de la mise à jour des préférences de partage de données"
  }
};

export const getBaseMessage = (code: MessageCode, language: Language = "fr") => {
  console.log("code:", code, "language:", language);
  return (
    MESSAGE_MAPPINGS[language][code] ||
    MESSAGE_MAPPINGS["en"][code] ||
    "Unknown error"
  );
};

export function extractErrorMessage(err: unknown) {
  const error = err as ApiError;
  return { message: error.message as MessageCode, code: error.status };
}
