import { ApiError } from "../types";
import { Language, MessageCode } from "../types/message";

export const MESSAGE_MAPPINGS = {
  "en": {
    "FOOD_NAME_REQUIRED": "Food name is required and cannot be empty",
    "FOOD_NAME_TOO_LONG": "Food name cannot exceed 100 characters",
    "CALORIES_MUST_BE_NUMBER": "Calories must be a valid number",
    "CALORIES_TOO_LOW": "Calories cannot be negative",
    "CALORIES_REQUIRED": "Calories field is required",
    "PROTEIN_MUST_BE_NUMBER": "Protein must be a valid number",
    "PROTEIN_TOO_LOW": "Protein cannot be negative",
    "PROTEIN_REQUIRED": "Protein field is required",
    "CARBS_MUST_BE_NUMBER": "Carbohydrates must be a valid number",
    "CARBS_TOO_LOW": "Carbohydrates cannot be negative",
    "CARBS_REQUIRED": "Carbohydrates field is required",
    "FAT_MUST_BE_NUMBER": "Fat must be a valid number",
    "FAT_TOO_LOW": "Fat cannot be negative",
    "FAT_REQUIRED": "Fat field is required",
    "FIBER_MUST_BE_NUMBER": "Fiber must be a valid number",
    "FIBER_TOO_LOW": "Fiber cannot be negative",
    "SUGAR_MUST_BE_NUMBER": "Sugar must be a valid number",
    "SUGAR_TOO_LOW": "Sugar cannot be negative",
    "SODIUM_MUST_BE_NUMBER": "Sodium must be a valid number",
    "SODIUM_TOO_LOW": "Sodium cannot be negative",
    "CATEGORY_MUST_BE_STRING": "Category must be a text value",
    "INVALID_CATEGORY": "Invalid food category selected",
    "BRAND_MUST_BE_STRING": "Brand must be a text value",
    "BARCODE_MUST_BE_STRING": "Barcode must be a text value",
    "SERVING_AMOUNT_MUST_BE_NUMBER": "Serving amount must be a valid number",
    "SERVING_AMOUNT_MUST_BE_POSITIVE": "Serving amount must be positive",
    "SERVING_UNIT_MUST_BE_STRING": "Serving unit must be a text value",
    "SERVING_SIZE_MUST_BE_OBJECT": "Serving size must be an object",
    "IS_PUBLIC_MUST_BE_BOOLEAN": "Public status must be true or false",
    "FOOD_ITEM_ID_REQUIRED": "Food item ID is required",
    "QUANTITY_MUST_BE_NUMBER": "Quantity must be a valid number",
    "QUANTITY_MUST_BE_POSITIVE": "Quantity must be positive",
    "QUANTITY_REQUIRED": "Quantity field is required",
    "UNIT_REQUIRED": "Unit field is required",
    "INVALID_UNIT": "Invalid unit selected",
    "MEAL_TYPE_REQUIRED": "Meal type field is required",
    "INVALID_MEAL_TYPE": "Invalid meal type selected",
    "INVALID_TIMESTAMP_FORMAT": "Invalid timestamp format",
    "TIMESTAMP_MUST_BE_ISO_FORMAT": "Timestamp must be in ISO format",
    "CALORIES_TOO_HIGH": "Daily calories cannot exceed 5000",
    "PROTEIN_TOO_HIGH": "Daily protein cannot exceed 300g",
    "CARBS_TOO_HIGH": "Daily carbohydrates cannot exceed 500g",
    "FAT_TOO_HIGH": "Daily fat cannot exceed 200g",
    "WATER_MUST_BE_NUMBER": "Water intake must be a valid number",
    "WATER_TOO_LOW": "Water intake cannot be less than 1000ml",
    "WATER_TOO_HIGH": "Water intake cannot exceed 5000ml",
    "WATER_REQUIRED": "Water intake field is required",
    "ACTIVITY_LEVEL_MUST_BE_STRING": "Activity level must be a text value",
    "INVALID_ACTIVITY_LEVEL": "Invalid activity level selected",
    "GOAL_MUST_BE_STRING": "Goal must be a text value",
    "INVALID_GOAL": "Invalid goal selected",
    "RECORD_CREATED": "Personal record added successfully",
    "RECORD_DELETED": "Personal record deleted successfully",
    "RECORD_UPDATED": "Personal record updated successfully",
    "SEARCH_QUERY_TOO_SHORT": "Search query must be at least 2 characters long",
    "GOALS_CREATED": "Nutrition goals created successfully",
    "GOALS_UPDATED": "Nutrition goals updated successfully",
    "MEAL_ADDED": "Meal added successfully",
    "PROFILE_NOT_FOUND": "Profile not found",
    "FOOD_NAME_AND_CALORIES_REQUIRED": "Food name and calories are required",
    "DATE_CANNOT_BE_PAST": "Date cannot be in the past",
  },
  "fr": {
    "FOOD_NAME_REQUIRED": "Le nom de l'aliment est requis et ne peut pas être vide",
    "FOOD_NAME_TOO_LONG": "Le nom de l'aliment ne peut pas dépasser 100 caractères",
    "CALORIES_MUST_BE_NUMBER": "Les calories doivent être un nombre valide",
    "CALORIES_TOO_LOW": "Les calories ne peuvent pas être négatives",
    "CALORIES_REQUIRED": "Le champ calories est obligatoire",
    "PROTEIN_MUST_BE_NUMBER": "Les protéines doivent être un nombre valide",
    "PROTEIN_TOO_LOW": "Les protéines ne peuvent pas être négatives",
    "PROTEIN_REQUIRED": "Le champ protéines est obligatoire",
    "CARBS_MUST_BE_NUMBER": "Les glucides doivent être un nombre valide",
    "CARBS_TOO_LOW": "Les glucides ne peuvent pas être négatives",
    "CARBS_REQUIRED": "Le champ glucides est obligatoire",
    "FAT_MUST_BE_NUMBER": "Les lipides doivent être un nombre valide",
    "FAT_TOO_LOW": "Les lipides ne peuvent pas être négatives",
    "FAT_REQUIRED": "Le champ lipides est obligatoire",
    "FIBER_MUST_BE_NUMBER": "Les fibres doivent être un nombre valide",
    "FIBER_TOO_LOW": "Les fibres ne peuvent pas être négatives",
    "SUGAR_MUST_BE_NUMBER": "Le sucre doit être un nombre valide",
    "SUGAR_TOO_LOW": "Le sucre ne peut pas être négatif",
    "SODIUM_MUST_BE_NUMBER": "Le sodium doit être un nombre valide",
    "SODIUM_TOO_LOW": "Le sodium ne peut pas être négatif",
    "CATEGORY_MUST_BE_STRING": "La catégorie doit être une valeur textuelle",
    "INVALID_CATEGORY": "Catégorie d'aliment invalide sélectionnée",
    "BRAND_MUST_BE_STRING": "La marque doit être une valeur textuelle",
    "BARCODE_MUST_BE_STRING": "Le code-barres doit être une valeur textuelle",
    "SERVING_AMOUNT_MUST_BE_NUMBER": "La quantité de portion doit être un nombre valide",
    "SERVING_AMOUNT_MUST_BE_POSITIVE": "La quantité de portion doit être positive",
    "SERVING_UNIT_MUST_BE_STRING": "L'unité de portion doit être une valeur textuelle",
    "SERVING_SIZE_MUST_BE_OBJECT": "La taille de portion doit être un objet",
    "IS_PUBLIC_MUST_BE_BOOLEAN": "Le statut public doit être vrai ou faux",
    "FOOD_ITEM_ID_REQUIRED": "L'ID de l'aliment est requis",
    "QUANTITY_MUST_BE_NUMBER": "La quantité doit être un nombre valide",
    "QUANTITY_MUST_BE_POSITIVE": "La quantité doit être positive",
    "QUANTITY_REQUIRED": "Le champ quantité est obligatoire",
    "UNIT_REQUIRED": "Le champ unité est obligatoire",
    "INVALID_UNIT": "Unité invalide sélectionnée",
    "MEAL_TYPE_REQUIRED": "Le champ type de repas est obligatoire",
    "INVALID_MEAL_TYPE": "Type de repas invalide sélectionné",
    "INVALID_TIMESTAMP_FORMAT": "Format d'horodatage invalide",
    "TIMESTAMP_MUST_BE_ISO_FORMAT": "L'horodatage doit être au format ISO",
     "CALORIES_TOO_HIGH": "Les calories quotidiennes ne peuvent pas dépasser 5000",
    "PROTEIN_TOO_HIGH": "Les protéines quotidiennes ne peuvent pas dépasser 300g",
    "CARBS_TOO_HIGH": "Les glucides quotidiens ne peuvent pas dépasser 500g",
    "FAT_TOO_HIGH": "Les lipides quotidiens ne peuvent pas dépasser 200g",
    "WATER_MUST_BE_NUMBER": "La consommation d'eau doit être un nombre valide",
    "WATER_TOO_LOW": "La consommation d'eau ne peut pas être inférieure à 1000ml",
    "WATER_TOO_HIGH": "La consommation d'eau ne peut pas dépasser 5000ml",
    "WATER_REQUIRED": "Le champ consommation d'eau est obligatoire",
    "ACTIVITY_LEVEL_MUST_BE_STRING": "Le niveau d'activité doit être une valeur textuelle",
    "INVALID_ACTIVITY_LEVEL": "Niveau d'activité invalide sélectionné",
    "GOAL_MUST_BE_STRING": "L'objectif doit être une valeur textuelle",
    "INVALID_GOAL": "Objectif invalide sélectionné",
    "RECORD_CREATED": "Record personnel ajouté avec succès",
    "RECORD_DELETED": "Record personnel supprimé avec succès",
    "RECORD_UPDATED": "Record personnel mis à jour avec succès",
    "SEARCH_QUERY_TOO_SHORT": "La requête de recherche doit contenir au moins 2 caractères",
    "GOALS_CREATED": "Objectifs nutritionnels créés avec succès",
    "GOALS_UPDATED": "Objectifs nutritionnels mis à jour avec succès",
    "MEAL_ADDED": "Repas ajouté avec succès",
    "PROFILE_NOT_FOUND": "Profil non trouvé",
    "FOOD_NAME_AND_CALORIES_REQUIRED": "Le nom de l'aliment et les calories sont requis",
    "DATE_CANNOT_BE_PAST": "La date du ne peut être une date passée"
  }
};

export const getBaseMessage = (language: Language, code: MessageCode) => {
  console.log("code:", code, "language:", language);
  return (
    MESSAGE_MAPPINGS[language][code] ||
    MESSAGE_MAPPINGS["en"][code] ||
    "Unknown error"
  );
};

export function extractErrorMessage(err: unknown) {
  const error = err as ApiError;
  return { message: error.message as MessageCode, code: error.status };
}
